name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv and Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }} # Handles both uv installation and version mapping in one step!

      - name: Install Dependencies
        run: uv sync --locked --dev

      - name: Install spacy models
        run: uv run python -m spacy download en_core_web_sm

      - name: Run tests
        run: uv run pytest tests -v --tb=short
